#ifndef RAYTRACING_DEMO_SCENE_RESOURCES_HLSLI
#define RAYTRACING_DEMO_SCENE_RESOURCES_HLSLI

#if !defined(RAYTRACING_DEMO_INLINE_BACKEND)
#define RAYTRACING_DEMO_INLINE_BACKEND 0
#endif

#include "../GBuffer/GBufferLayout.hlsli"
#include "SceneCamera.hlsli"
#include "SceneGeometry.hlsli"
#include "SceneLighting.hlsli"

#if RAYTRACING_DEMO_INLINE_BACKEND
#include <ShaderLibrary/Common/RootSignature.hlsli>
#include <ShaderLibrary/RayTracing/InlineRayTracing.hlsli>
#endif

#if RAYTRACING_DEMO_INLINE_BACKEND

#define RAYTRACING_DEMO_INLINE_TEXTURE_SPACE space5
#define RAYTRACING_DEMO_INLINE_VERTEX_BUFFER_SPACE space6
#define RAYTRACING_DEMO_INLINE_INDEX_BUFFER_SPACE space7
#define RAYTRACING_DEMO_SCENE g_InlineRayTracingScene
#define RAYTRACING_DEMO_GBUFFER_REGISTER register(t0, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_DEPTH_REGISTER register(t5, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_SKYBOX_REGISTER register(t6, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_MATERIALS_REGISTER register(t7, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_GEOMETRIES_REGISTER register(t8, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_DIRECTIONAL_LIGHTS_REGISTER register(t9, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_POINT_LIGHTS_REGISTER register(t10, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_AREA_LIGHTS_REGISTER register(t11, COMMON_ROOT_SIGNATURE_PIPELINE_SPACE)
#define RAYTRACING_DEMO_TEXTURES_REGISTER register(t0, RAYTRACING_DEMO_INLINE_TEXTURE_SPACE)
#define RAYTRACING_DEMO_VERTEX_BUFFERS_REGISTER register(t0, RAYTRACING_DEMO_INLINE_VERTEX_BUFFER_SPACE)
#define RAYTRACING_DEMO_INDEX_BUFFERS_REGISTER register(t0, RAYTRACING_DEMO_INLINE_INDEX_BUFFER_SPACE)
#define RAYTRACING_DEMO_OUTPUT_REGISTER register(u0)
#define RAYTRACING_DEMO_ACCUMULATION_REGISTER register(u1)
#define RAYTRACING_DEMO_NRD_NOISY_RADIANCE_REGISTER register(u2)
#define RAYTRACING_DEMO_LINEAR_SAMPLER_REGISTER register(s1)

#else

#define RAYTRACING_DEMO_SCENE Scene
#define RAYTRACING_DEMO_GBUFFER_REGISTER register(t0, space4)
#define RAYTRACING_DEMO_DEPTH_REGISTER register(t0, space6)
#define RAYTRACING_DEMO_SKYBOX_REGISTER register(t0, space5)
#define RAYTRACING_DEMO_MATERIALS_REGISTER register(t1, space0)
#define RAYTRACING_DEMO_GEOMETRIES_REGISTER register(t2, space0)
#define RAYTRACING_DEMO_DIRECTIONAL_LIGHTS_REGISTER register(t3, space0)
#define RAYTRACING_DEMO_POINT_LIGHTS_REGISTER register(t4, space0)
#define RAYTRACING_DEMO_AREA_LIGHTS_REGISTER register(t5, space0)
#define RAYTRACING_DEMO_TEXTURES_REGISTER register(t0, space3)
#define RAYTRACING_DEMO_VERTEX_BUFFERS_REGISTER register(t0, space1)
#define RAYTRACING_DEMO_INDEX_BUFFERS_REGISTER register(t0, space2)
#define RAYTRACING_DEMO_OUTPUT_REGISTER register(u0, space0)
#define RAYTRACING_DEMO_ACCUMULATION_REGISTER register(u1, space0)
#define RAYTRACING_DEMO_NRD_NOISY_RADIANCE_REGISTER register(u2, space0)
#define RAYTRACING_DEMO_LINEAR_SAMPLER_REGISTER register(s0)

RaytracingAccelerationStructure Scene : register(t0, space0);

#endif

Texture2D<float4> GBufferTextures
    [GBuffer_Count]
    : RAYTRACING_DEMO_GBUFFER_REGISTER;

Texture2D<float> DepthTexture : RAYTRACING_DEMO_DEPTH_REGISTER;
TextureCube Skybox : RAYTRACING_DEMO_SKYBOX_REGISTER;
StructuredBuffer<MaterialData> Materials : RAYTRACING_DEMO_MATERIALS_REGISTER;
StructuredBuffer<GeometryData> Geometries : RAYTRACING_DEMO_GEOMETRIES_REGISTER;
StructuredBuffer<DirectionalLightData> DirectionalLights : RAYTRACING_DEMO_DIRECTIONAL_LIGHTS_REGISTER;
StructuredBuffer<PointLightData> PointLights : RAYTRACING_DEMO_POINT_LIGHTS_REGISTER;
StructuredBuffer<AreaLightData> AreaLights : RAYTRACING_DEMO_AREA_LIGHTS_REGISTER;

Texture2D<float4> Textures
    []
    : RAYTRACING_DEMO_TEXTURES_REGISTER;

StructuredBuffer<VertexAttributes> VertexBuffers
    []
    : RAYTRACING_DEMO_VERTEX_BUFFERS_REGISTER;

Buffer<uint> IndexBuffers
    []
    : RAYTRACING_DEMO_INDEX_BUFFERS_REGISTER;

RWTexture2D<float4> Output : RAYTRACING_DEMO_OUTPUT_REGISTER;
RWTexture2D<float4> Accumulation : RAYTRACING_DEMO_ACCUMULATION_REGISTER;
RWTexture2D<float4> NrdNoisyRadiance : RAYTRACING_DEMO_NRD_NOISY_RADIANCE_REGISTER;
SamplerState LinearWrapSampler : RAYTRACING_DEMO_LINEAR_SAMPLER_REGISTER;

#endif
